services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq


  sqldb:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: 'sqlserver'
    ports:
        - 1433:1433
    volumes:             
        - ./init:/docker-entrypoint-initdb.d
    environment:
        MSSQL_SA_PASSWORD: "Password123!"
        ACCEPT_EULA: "Y"


  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: 'mongodb'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - type: bind
        source: ./data
        target: /data/db